"""Generic comment extraction across many source-file languages.

The idea: any .ts / .py / .yml / .tf / .go / .rs / … file might carry
intent in its comments — module-level headers, JSDoc blocks, TODO
paragraphs, tribal-knowledge asides. We pull those out via a small
per-extension rules table (one dict entry = one new language supported)
and pass them to the same Claude extractor the docs ingester uses.

Scope of this module is deliberately narrow:
- extract substantive comments from files
- drop license boilerplate, lint pragmas, and tiny chunks
- emit one `RawArtifact` per file (or per block, with --per-block)

Everything else — extraction quality, deduping, linking — happens
downstream in the existing pipeline.
"""

from __future__ import annotations

import re
from collections.abc import Iterator
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from argos.models import RawArtifact, Source


# Per-extension comment-syntax rules. Adding a language = one entry.
#
# Each entry may declare:
#   line:       prefix for single-line comments
#   block:      (open, close) tuple for multi-line comments
#   doc:        (open, close) for doc-style blocks (higher signal)
#   outer_doc:  line prefix for outer doc comments (Rust's `///`)
COMMENT_RULES: dict[str, dict] = {
    # C-family
    ".ts":   {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".tsx":  {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".js":   {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".jsx":  {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".mjs":  {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".cjs":  {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".go":   {"line": "//", "block": ("/*", "*/")},
    ".rs":   {"line": "//", "block": ("/*", "*/"), "outer_doc": "///"},
    ".c":    {"line": "//", "block": ("/*", "*/")},
    ".h":    {"line": "//", "block": ("/*", "*/")},
    ".cc":   {"line": "//", "block": ("/*", "*/")},
    ".cpp":  {"line": "//", "block": ("/*", "*/")},
    ".hpp":  {"line": "//", "block": ("/*", "*/")},
    ".cs":   {"line": "//", "block": ("/*", "*/")},
    ".java": {"line": "//", "block": ("/*", "*/")},
    ".kt":   {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".swift": {"line": "//", "block": ("/*", "*/"), "doc": ("/**", "*/")},
    ".scala": {"line": "//", "block": ("/*", "*/")},
    ".dart": {"line": "//", "block": ("/*", "*/")},
    # Hash-style
    ".py":   {"line": "#", "block": ('"""', '"""')},
    ".rb":   {"line": "#"},
    ".sh":   {"line": "#"},
    ".bash": {"line": "#"},
    ".zsh":  {"line": "#"},
    ".fish": {"line": "#"},
    ".ps1":  {"line": "#"},
    ".yml":  {"line": "#"},
    ".yaml": {"line": "#"},
    ".toml": {"line": "#"},
    ".conf": {"line": "#"},
    ".ini":  {"line": ";"},
    # HCL
    ".tf":   {"line": "#", "block": ("/*", "*/")},
    ".hcl":  {"line": "#", "block": ("/*", "*/")},
    # SQL / Lua
    ".sql":  {"line": "--", "block": ("/*", "*/")},
    ".lua":  {"line": "--", "block": ("--[[", "]]")},
    # Markup
    ".html": {"block": ("<!--", "-->")},
    ".xml":  {"block": ("<!--", "-->")},
    ".svg":  {"block": ("<!--", "-->")},
}


# Noise patterns: if any match a comment's body, the block is skipped.
# Covers license preambles, lint pragmas, codegen notices, decorators-as-
# comments. Kept conservative — better to pass noise to the extractor (which
# will also filter) than to drop real signal.
NOISE_PATTERNS = [
    re.compile(r"copyright\s+(?:\(c\)\s*)?\d{4}", re.IGNORECASE),
    re.compile(r"licensed\s+under\s+the", re.IGNORECASE),
    re.compile(r"spdx-license-identifier", re.IGNORECASE),
    re.compile(r"all\s+rights\s+reserved", re.IGNORECASE),
    re.compile(r"auto-generated|autogenerated|do\s*not\s*edit", re.IGNORECASE),
    re.compile(r"this\s+file\s+was\s+generated", re.IGNORECASE),
    re.compile(
        r"eslint-(disable|enable)|@ts-(ignore|nocheck|expect-error)|prettier-ignore",
        re.IGNORECASE,
    ),
    re.compile(r"(?:^|\s)(?:noqa|type:\s*ignore|pylint:\s*disable)", re.IGNORECASE),
    re.compile(r"istanbul\s+ignore|c8\s+ignore", re.IGNORECASE),
]


# Paths (directory names) always skipped.
DEFAULT_EXCLUDES: frozenset[str] = frozenset(
    {
        ".git",
        ".svn",
        ".hg",
        "node_modules",
        ".venv",
        "venv",
        "env",
        "dist",
        "build",
        "target",
        "out",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        "coverage",
        ".coverage",
        ".next",
        ".turbo",
        ".nuxt",
        ".cache",
        ".parcel-cache",
        "vendor",
        "third_party",
        "third-party",
        "bower_components",
    }
)


@dataclass
class CommentBlock:
    start: int  # 1-indexed
    end: int
    kind: str  # "line_group" | "block" | "doc" | "outer_doc"
    body: str
    following_symbol: str | None = None  # hint: next non-blank non-comment line


@dataclass
class ExtractedFile:
    path: Path
    rel: Path
    blocks: list[CommentBlock] = field(default_factory=list)
    size: int = 0


class CommentExtractor:
    """Walk a repository tree, yield `RawArtifact` per source file whose
    comments carry substance. Language-agnostic via the rules table."""

    def __init__(
        self,
        root: Path,
        *,
        excludes: frozenset[str] = DEFAULT_EXCLUDES,
        extensions: tuple[str, ...] | None = None,
        per_block: bool = False,
        min_chars: int = 120,
        min_lines: int = 3,
    ) -> None:
        self.root = root.resolve()
        self.excludes = excludes
        self.extensions = extensions or tuple(COMMENT_RULES.keys())
        self.per_block = per_block
        self.min_chars = min_chars
        self.min_lines = min_lines

    def iter_files(self) -> Iterator[Path]:
        for path in sorted(self.root.rglob("*")):
            if not path.is_file():
                continue
            try:
                rel = path.relative_to(self.root)
            except ValueError:
                continue
            if any(part in self.excludes for part in rel.parts):
                continue
            if path.suffix.lower() not in self.extensions:
                continue
            yield path

    def iter_artifacts(
        self, *, max_items: int | None = None
    ) -> Iterator[RawArtifact]:
        count = 0
        for path in self.iter_files():
            rules = COMMENT_RULES.get(path.suffix.lower())
            if not rules:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue

            rel = path.relative_to(self.root)
            blocks = list(_extract_blocks(text, rules))
            kept = [
                b
                for b in blocks
                if _is_substantial(b.body, self.min_chars, self.min_lines)
                and not _is_noise(b.body)
            ]
            if not kept:
                continue

            if self.per_block:
                for block in kept:
                    yield _make_artifact(path, rel, text, [block])
                    count += 1
                    if max_items and count >= max_items:
                        return
            else:
                yield _make_artifact(path, rel, text, kept)
                count += 1
                if max_items and count >= max_items:
                    return


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def _make_artifact(
    path: Path, rel: Path, full_text: str, blocks: list[CommentBlock]
) -> RawArtifact:
    """Assemble a RawArtifact whose body shows each block with its line
    range and the symbol it attaches to (when detectable)."""
    sections: list[str] = [f"File: {rel.as_posix()}"]
    lang = path.suffix.lower().lstrip(".")
    sections.append(f"Language: {lang}")
    sections.append("")

    for b in blocks:
        header = f"— lines {b.start}-{b.end} ({b.kind})"
        if b.following_symbol:
            header += f"  →  {b.following_symbol}"
        sections.append(header)
        sections.append(b.body.strip())
        sections.append("")

    body = "\n".join(sections).strip()

    try:
        mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    except OSError:
        mtime = None

    total_lines = sum(b.end - b.start + 1 for b in blocks)
    file_lines = full_text.count("\n") + 1

    return RawArtifact(
        source=Source(
            kind="local",
            url=None,
            ref=rel.as_posix(),
            fetched_at=datetime.now(timezone.utc),
        ),
        title=rel.as_posix(),
        body=body,
        author=None,
        created_at=mtime,
        extras={
            "path": str(path),
            "language": lang,
            "blocks": len(blocks),
            "comment_lines": total_lines,
            "file_lines": file_lines,
        },
    )


def _extract_blocks(text: str, rules: dict) -> Iterator[CommentBlock]:
    """Walk `text` line-by-line, yielding coalesced comment blocks per rules."""
    lines = text.splitlines()
    n = len(lines)
    i = 0

    line_marker: str | None = rules.get("line")
    block = rules.get("block")
    block_open, block_close = (block[0], block[1]) if block else (None, None)
    doc = rules.get("doc")
    doc_open, doc_close = (doc[0], doc[1]) if doc else (None, None)
    outer_doc: str | None = rules.get("outer_doc")

    def symbol_after(idx: int) -> str | None:
        # Peek the next 3 non-blank non-comment lines; use the first one
        # as a hint about what the comment above was describing.
        for k in range(idx, min(idx + 5, n)):
            ln = lines[k].strip()
            if not ln:
                continue
            if line_marker and ln.startswith(line_marker):
                continue
            if block_open and ln.startswith(block_open):
                continue
            if outer_doc and ln.startswith(outer_doc):
                continue
            return ln[:100]
        return None

    while i < n:
        line = lines[i]
        stripped = line.lstrip()

        # Doc block first (distinguishes /** … */ from /* … */)
        if doc_open and stripped.startswith(doc_open) and doc_close:
            start = i
            rest = stripped[len(doc_open) :]
            if doc_close in rest:
                body = rest[: rest.rfind(doc_close)]
                i += 1
                yield CommentBlock(
                    start + 1, i, "doc", _clean_block(body), symbol_after(i)
                )
                continue
            buf = [rest]
            i += 1
            while i < n and doc_close not in lines[i]:
                buf.append(lines[i])
                i += 1
            if i < n:
                tail = lines[i]
                buf.append(tail[: tail.find(doc_close)])
                i += 1
            yield CommentBlock(
                start + 1, i, "doc", _clean_block("\n".join(buf)), symbol_after(i)
            )
            continue

        # Plain block comment
        if block_open and stripped.startswith(block_open) and block_close:
            start = i
            rest = stripped[len(block_open) :]
            if block_close in rest:
                body = rest[: rest.rfind(block_close)]
                i += 1
                yield CommentBlock(
                    start + 1, i, "block", _clean_block(body), symbol_after(i)
                )
                continue
            buf = [rest]
            i += 1
            while i < n and block_close not in lines[i]:
                buf.append(lines[i])
                i += 1
            if i < n:
                tail = lines[i]
                buf.append(tail[: tail.find(block_close)])
                i += 1
            yield CommentBlock(
                start + 1, i, "block", _clean_block("\n".join(buf)), symbol_after(i)
            )
            continue

        # Outer-doc lines (Rust `///`, coalesce consecutive)
        if outer_doc and stripped.startswith(outer_doc):
            start = i
            buf = [stripped[len(outer_doc) :].strip()]
            i += 1
            while i < n and lines[i].lstrip().startswith(outer_doc):
                buf.append(lines[i].lstrip()[len(outer_doc) :].strip())
                i += 1
            yield CommentBlock(
                start + 1, i, "outer_doc", "\n".join(buf).strip(), symbol_after(i)
            )
            continue

        # Plain line comments — coalesce a contiguous run into one "group"
        if line_marker and stripped.startswith(line_marker):
            # Ignore shebangs
            if stripped.startswith("#!") and i == 0:
                i += 1
                continue
            start = i
            buf = [stripped[len(line_marker) :].strip()]
            i += 1
            while i < n and lines[i].lstrip().startswith(line_marker):
                buf.append(lines[i].lstrip()[len(line_marker) :].strip())
                i += 1
            yield CommentBlock(
                start + 1, i, "line_group", "\n".join(buf).strip(), symbol_after(i)
            )
            continue

        i += 1


def _clean_block(body: str) -> str:
    """Strip leading `*` or whitespace from block-comment interior lines."""
    out: list[str] = []
    for raw in body.splitlines():
        s = raw.strip()
        if s.startswith("*") and not s.startswith("*/"):
            s = s[1:].strip()
        out.append(s)
    # Drop leading/trailing blank lines, preserve internal spacing.
    while out and not out[0]:
        out.pop(0)
    while out and not out[-1]:
        out.pop()
    return "\n".join(out).strip()


def _is_substantial(body: str, min_chars: int, min_lines: int) -> bool:
    text = body.strip()
    if len(text) >= min_chars:
        return True
    non_trivial = [line for line in text.splitlines() if len(line.strip()) >= 20]
    return len(non_trivial) >= min_lines


def _is_noise(body: str) -> bool:
    return any(p.search(body) for p in NOISE_PATTERNS)
